[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['pnpm install --no-frozen-lockfile']

[phases.build]
cmds = [
  'cd packages/db && pnpm db:generate',
  'cd apps/web && pnpm build'
]

[start]
cmd = 'cd apps/web && pnpm start'

[variables]
PORT = '3000'
