[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['pnpm install --no-frozen-lockfile']

[phases.build]
cmds = [
  'ls -la',
  'pwd',
  'cat turbo.json',
  'pnpm build'
]

[start]
cmd = 'pnpm start'
